name: gdcPipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.14
  - anyio=4.11.0
  - argcomplete=3.6.3
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - binutils=2.45
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bioconductor-data-packages=20250625
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.11.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - conda-gcc-specs=14.3.0
  - contourpy=1.3.3
  - curl=8.17.0
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.6
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.0
  - font-ttf-source-code-pro=2.38
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=11.0.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jq=1.8.1
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - king=2.2.7
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libcxxabi=21.1.6
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=17.7
  - libsanitizer=14.3.0
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libuv=1.51.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=8.0.1
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.10.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - oniguruma=6.9.10
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openmp=8.0.1
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.2.1
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.5
  - pcre2=10.44
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plink2=2.0.0a.6.9
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base
  - r-base64enc=0.1.3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-boot=1.3.30
  - r-brio=1.1.5
  - r-broom=1.0.6
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=6.0.94
  - r-cellranger=1.1.0
  - r-class=7.3.22
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-codetools=0.2.20
  - r-colorspace=2.1.0
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=5.1.0
  - r-data.table=1.15.4
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-desc=1.4.3
  - r-diagram=1.6.5
  - r-diffobj=0.3.5
  - r-digest=0.6.36
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7.14
  - r-ellipsis=0.3.2
  - r-evaluate=0.24.0
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-formatr=1.14
  - r-formula.tools=1.7.1
  - r-fs=1.6.4
  - r-future=1.33.2
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-gbrd=0.4.12
  - r-generics=0.1.3
  - r-ggplot2=3.5.1
  - r-glmnet=4.1.8
  - r-globals=0.16.3
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gtable
  - r-gwasexacthw=1.2
  - r-hardhat=1.4.0
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-ipred=0.9.14
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jomo=2.7.6
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23.24
  - r-knitr=1.47
  - r-labeling=0.4.3
  - r-lattice=0.22.6
  - r-lava=1.7.3
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1.35.3
  - r-lmtest=0.9.40
  - r-logistf=1.26.0
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3.60.0.1
  - r-matrix=1.6.5
  - r-matrixmodels=0.5.3
  - r-matrixstats=1.3.0
  - r-memoise=2.0.1
  - r-mgcv=1.9.1
  - r-mice=3.16.0
  - r-mime=0.12
  - r-minqa=1.2.7
  - r-mitml=0.4.5
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1.165
  - r-nloptr=2.0.3
  - r-nnet=7.3.19
  - r-numderiv=2016.8.1.1
  - r-openssl=2.2.0
  - r-operator.tools=1.6.3
  - r-ordinal=2023.12.4
  - r-pan=1.9
  - r-parallelly=1.37.1
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgload=1.3.4
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2024.6.25
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-proxy=0.4.27
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quantreg=5.98
  - r-r6=2.5.1
  - r-ragg=1.3.2
  - r-rappdirs=0.3.3
  - r-rbibutils=2.2.16
  - r-rcolorbrewer=1.1.3
  - r-rcpp=1.0.12
  - r-rcpparmadillo=0.12.8.4.0
  - r-rcppeigen=0.3.4.0.0
  - r-rdpack=2.6
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.10
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.0
  - r-reshape2
  - r-rlang=1.1.4
  - r-rmarkdown=2.27
  - r-rpart=4.1.23
  - r-rprojroot=2.0.4
  - r-rsqlite=2.3.4
  - r-rstudioapi=0.16.0
  - r-rvest=1.0.4
  - r-sandwich=3.1.0
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-selectr=0.4.2
  - r-shape=1.4.6.1
  - r-sparsem=1.84
  - r-squarem=2021.1
  - r-stringi=1.7.6
  - r-stringr=1.5.1
  - r-survival=3.7.0
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-testthat=3.2.1.1
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.51
  - r-tzdb=0.4.0
  - r-ucminf=1.2.1
  - r-utf8=1.2.4
  - r-uuid=1.2.0
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.5.2
  - r-withr=3.0.0
  - r-xfun=0.45
  - r-xml2=1.3.6
  - r-yaml=2.3.8
  - r-zoo=1.8.12
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.29.0
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - sysroot_linux-64=2.39
  - terminado=0.18.1
  - tinycss2=1.5.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.3.0
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - perl
  - bioconductor-gdsfmt
  - bioconductor-snprelate
  - bioconductor-seqarray
  - bioconductor-seqvartools
  - bioconductor-biocparallel
  - r-hdpca
  - bioconductor-gwastools
  - bioconductor-genesis
  - bioconductor-xvector
  - bioconductor-biostrings
  - bcftools
  - openjdk
  - plink
  - rfmix
  - git
  - keras
  - tensorflow
  - nibabel
  - pandas-plink
  - pytest
  - scikit-learn
  - seaborn
  - statsmodels
  - xarray
  - crossmap
  - fraposa-pgsc
  - shapeit
  - quarto
prefix: /projects/standard/gdc/public/envs/gdcPipeline
