$schema: "http://json-schema.org/draft-07/schema#"
description: "Configuration for the GDC QC pipeline"
type: object

INPUT_FILE: 
    description: "Path to the input file"
OUT_DIR:
    description: "Path to the output directory"
REF:
    description: "Path to the reference directory"

relatedness: 
    method
    

    wildcard_constraints:
        stage = "01-Initialfilter|02-relatedness|03-Standardfilter|04-AncestryEstimation|05-AncestryFilters"
        prefix = "initialFiltered|unrelated|related"
